# See http://about.travis-ci.org/docs/user/build-configuration/
# and
language: scala
scala:
    - 2.11.6
branches:
  only:
    - master
notifications:
  email:
    recipients:
      - opensource@gonitro.com
jdk:
    - oraclejdk7
    - oraclejdk8

script:
    - sbt fastOptJS
    - sbt test